#!/usr/bin/env ruby

if ENV['RAILS_ENV'] == 'test'
  require 'simplecov'

  # Save to CircleCI's artifacts directory if we're on CircleCI
  if ENV['CIRCLE_ARTIFACTS']
    dir = File.join(ENV['CIRCLE_ARTIFACTS'], "coverage")
    SimpleCov.coverage_dir(dir)
  end

  SimpleCov.start 'rails' do
    add_filter 'config/application'
  end
end

APP_PATH = File.expand_path('../config/application', __dir__)
require_relative '../config/boot'
require 'rails/commands'
